// Triangle Startup Events — mock dataset for June 2026
// Schema mirrors the scraper output. friendly_date is pre-rendered.

window.TRIANGLE_EVENTS = [
  {
    id: "e01",
    name: "Triangle Startup Collective — June Meeting",
    date: "2026-06-04", start_time: "17:45", end_time: "20:30",
    location: "Raleigh Founded, 509 W North St, Raleigh",
    city: "Raleigh",
    event_type: "Panel",
    audience: ["Founders"],
    topic_tags: ["networking", "panel discussion", "startup founders"],
    description: "Monthly meetup featuring startup founders and teams with a panel of experts for practical conversations about building companies from the ground up.",
    source_url: "https://www.meetup.com/triangle-startup-collective/",
    friendly_date: "Thursday, June 4 · 5:45pm–8:30pm",
    host: "Triangle Startup Collective",
    editors_pick: true,
  },
  {
    id: "e02",
    name: "Founder Friday Lunch",
    date: "2026-06-05", start_time: "12:00", end_time: "13:30",
    location: "American Underground, 201 W Main St, Durham",
    city: "Durham",
    event_type: "Networking",
    audience: ["Founders"],
    topic_tags: ["networking", "lunch"],
    description: "Bring your lunch. Meet 8–10 other founders. No pitches, no slides — just real conversations about what you're actually working on.",
    source_url: "https://luma.com/founder-friday",
    friendly_date: "Friday, June 5 · 12:00pm–1:30pm",
    host: "American Underground",
  },
  {
    id: "e03",
    name: "AI Tinkerers Triangle",
    date: "2026-06-08", start_time: "18:00", end_time: "20:00",
    location: "Loading Dock, 807 E Main St, Durham",
    city: "Durham",
    event_type: "Workshop",
    audience: ["Engineers", "Founders"],
    topic_tags: ["AI", "machine learning", "workshop"],
    description: "Monthly hands-on session for builders shipping with LLMs. Bring a laptop and a half-built idea. Lightning demos, open hacking, and pizza.",
    source_url: "https://aitinkerers.org/triangle",
    friendly_date: "Monday, June 8 · 6:00pm–8:00pm",
    host: "AI Tinkerers",
    editors_pick: true,
  },
  {
    id: "e04",
    name: "Pitch Practice Workshop",
    date: "2026-06-10", start_time: "09:00", end_time: "12:00",
    location: "First Flight Venture Center, Research Triangle Park",
    city: "RTP",
    event_type: "Workshop",
    audience: ["Founders"],
    topic_tags: ["fundraising", "pitch", "workshop"],
    description: "Three-hour intensive on your 2-minute pitch. Live feedback from operators who've raised $10M+. Bring a deck or just an idea.",
    source_url: "https://luma.com/pitch-practice",
    friendly_date: "Wednesday, June 10 · 9:00am–12:00pm",
    host: "First Flight Venture Center",
  },
  {
    id: "e05",
    name: "Build in Public Happy Hour",
    date: "2026-06-11", start_time: "17:30", end_time: "19:30",
    location: "Trophy Brewing, 656 Maywood Ave, Raleigh",
    city: "Raleigh",
    event_type: "Happy Hour",
    audience: ["Founders", "Engineers"],
    topic_tags: ["networking", "happy hour", "build in public"],
    description: "Monthly drink-up for people building in public. Show the thing you shipped this month. First round on us.",
    source_url: "https://luma.com/bip-rdu",
    friendly_date: "Thursday, June 11 · 5:30pm–7:30pm",
    host: "Build in Public Triangle",
  },
  {
    id: "e06",
    name: "Founder Coffee Chapel Hill",
    date: "2026-06-12", start_time: "08:00", end_time: "10:00",
    location: "Caribou Coffee, 200 W Franklin St, Chapel Hill",
    city: "Chapel Hill",
    event_type: "Networking",
    audience: ["Founders"],
    topic_tags: ["networking", "coffee"],
    description: "Drop in any time. Casual founder meet-up — no agenda, no name tags. Just coffee and conversation.",
    source_url: "https://www.meetup.com/founder-coffee-ch/",
    friendly_date: "Friday, June 12 · 8:00am–10:00am",
    host: "Founder Coffee CH",
  },
  {
    id: "e07",
    name: "Hardware Founders Meetup",
    date: "2026-06-15", start_time: "18:00", end_time: "20:30",
    location: "Boxyard RTP, 900 Park Offices Dr, Durham",
    city: "Durham",
    event_type: "Talk",
    audience: ["Founders", "Engineers"],
    topic_tags: ["hardware", "manufacturing", "founders"],
    description: "Two short talks from Triangle hardware founders — one shipped robotics, one shipped consumer electronics. Lessons from getting atoms out the door.",
    source_url: "https://luma.com/hardware-founders",
    friendly_date: "Monday, June 15 · 6:00pm–8:30pm",
    host: "Triangle Hardware",
  },
  {
    id: "e08",
    name: "Fundraising 101: From First Check to Seed",
    date: "2026-06-17", start_time: "12:00", end_time: "13:00",
    location: "HQ Raleigh, 310 S Harrington St, Raleigh",
    city: "Raleigh",
    event_type: "Talk",
    audience: ["Founders"],
    topic_tags: ["fundraising", "talk"],
    description: "Brown-bag session with two early-stage investors. What they look for, what kills a deal, and how to actually run a round.",
    source_url: "https://luma.com/fundraising-101",
    friendly_date: "Wednesday, June 17 · 12:00pm–1:00pm",
    host: "HQ Raleigh",
  },
  {
    id: "e09",
    name: "Demo Night: Spring Cohort Showcase",
    date: "2026-06-18", start_time: "18:00", end_time: "21:00",
    location: "American Underground, 201 W Main St, Durham",
    city: "Durham",
    event_type: "Demo Day",
    audience: ["Founders", "Investors"],
    topic_tags: ["demo day", "fundraising", "showcase"],
    description: "Twelve startups, three minutes each. Live Q&A after. Investors, operators, and the merely curious — all welcome.",
    source_url: "https://luma.com/demo-night-spring",
    friendly_date: "Thursday, June 18 · 6:00pm–9:00pm",
    host: "American Underground",
    editors_pick: true,
  },
  {
    id: "e10",
    name: "Designers Meet Founders",
    date: "2026-06-19", start_time: "16:00", end_time: "18:00",
    location: "Raleigh Founded, 509 W North St, Raleigh",
    city: "Raleigh",
    event_type: "Happy Hour",
    audience: ["Designers", "Founders"],
    topic_tags: ["design", "networking"],
    description: "A casual mixer for product designers and the founders who need them. Bring a portfolio or just bring yourself.",
    source_url: "https://luma.com/designers-meet-founders",
    friendly_date: "Friday, June 19 · 4:00pm–6:00pm",
    host: "Triangle Design Co.",
  },
  {
    id: "e11",
    name: "RDSCo Volunteer Mixer",
    date: "2026-06-23", start_time: "18:00", end_time: "20:00",
    location: "Loading Dock, 807 E Main St, Durham",
    city: "Durham",
    event_type: "Networking",
    audience: ["Founders", "Designers", "Engineers", "Investors"],
    topic_tags: ["volunteer", "community", "rdsw"],
    description: "Help shape RDSW 2027. We're looking for volunteers across programming, ops, and design. Snacks, drinks, and a real chance to plug in.",
    source_url: "https://www.raleighdurhamstartup.co/volunteer",
    friendly_date: "Tuesday, June 23 · 6:00pm–8:00pm",
    host: "Raleigh-Durham Startup Co.",
  },
  {
    id: "e12",
    name: "Triangle Tech Day",
    date: "2026-06-24", start_time: "09:00", end_time: "17:00",
    location: "Frontier RTP, 800 Park Offices Dr, RTP",
    city: "RTP",
    event_type: "Talk",
    audience: ["Engineers", "Founders"],
    topic_tags: ["engineering", "AI", "talk"],
    description: "Full-day single-track conference. Eight talks across systems, AI infra, and developer tooling. Lunch included.",
    source_url: "https://luma.com/triangle-tech-day",
    friendly_date: "Wednesday, June 24 · 9:00am–5:00pm",
    host: "Frontier RTP",
  },
  {
    id: "e13",
    name: "Startup Karaoke",
    date: "2026-06-25", start_time: "19:00", end_time: "22:00",
    location: "Ruby Deluxe, 415 S Salisbury St, Raleigh",
    city: "Raleigh",
    event_type: "Happy Hour",
    audience: ["Founders", "Designers", "Engineers", "Investors"],
    topic_tags: ["social", "karaoke", "fun"],
    description: "Sing your runway away. Open mic, open bar tab for the first 30 minutes. Pitches over the mic strongly discouraged.",
    source_url: "https://luma.com/startup-karaoke",
    friendly_date: "Thursday, June 25 · 7:00pm–10:00pm",
    host: "Triangle Founders",
  },
  {
    id: "e14",
    name: "First-Time Founder AMA",
    date: "2026-06-29", start_time: "12:00", end_time: "13:30",
    location: "HQ Raleigh, 310 S Harrington St, Raleigh",
    city: "Raleigh",
    event_type: "Panel",
    audience: ["Founders"],
    topic_tags: ["panel", "founders", "AMA"],
    description: "Three founders who shipped a product in their first 12 months. Honest stories about the messy middle. Audience-driven Q&A.",
    source_url: "https://luma.com/first-time-founder-ama",
    friendly_date: "Monday, June 29 · 12:00pm–1:30pm",
    host: "HQ Raleigh",
  },
];

// Color tokens per event_type (RDSW accent palette)
window.EVENT_TYPE_STYLES = {
  "Talk":        { dot: "#FFB648", soft: "#FFE9C2", deep: "#E68A00" },
  "Panel":       { dot: "#FC7777", soft: "#FDDADA", deep: "#E10505" },
  "Workshop":    { dot: "#B577FC", soft: "#E6D3FE", deep: "#6B05E1" },
  "Happy Hour":  { dot: "#1BE0B0", soft: "#C7F5E6", deep: "#009F97" },
  "Networking":  { dot: "#009DE0", soft: "#C9E9F7", deep: "#003D69" },
  "Demo Day":    { dot: "#003D69", soft: "#D5DEE6", deep: "#001A2E" },
};

// "Today" anchor for the prototype — June 11, 2026 — so the demo lands mid-month
// with past + future events visible.
window.PROTO_TODAY = new Date(2026, 5, 11);
